spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicalplatform?createDatabaseIfNotExist=true
    username: root
    password: ronaldica1
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL55Dialect
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

#jwt:
#  secret: javainuse